# 基本配置
exp_name: s1
split_seed: 1449
seed: 909
fold: 0

# 训练设置
pre_epoch: 40
num_epoch: 140
inc_mode: lin
stage_transition_epoch: 80
device: [0]
batch_size: 33
test_batch_size: 33

# 优化器
optimizer: SGD
base_lr: 0.0001
base_lr_mask: 4
weight_decay: 0.0005
nesterov: True
scheduler: auto
stepsize: 10
gamma: 0.5

# 损失权重
LC: 1
LO: 1
LCI: 1
LCV: 1
LG: 0.002

# 数据
data_dir: ADvsCN.ex001_2_p288
data_name: ADvsCN.ex001_2_p288_pw24_all
patch_size: 24
feeder: tools.feeder.FeederGraph
train_feeder_args:
  debug: False
  save: False
test_feeder_args:
  debug: False
  save: False

# 图构建
graph_args:
  node_type: px
  edge_type: abscorr
  dist_type: euc_1+gau
  adj_norm: DAD

# 模型
model: net.networks
model_args:
  hidden1: [28]
  kernels: [2]
  hidden2: [28,28]
  freeze_extractor: True

# DenseNet预训练设置 (新增)
auto_pretrain_densenet: True  # 是否自动使用对应折的预训练DenseNet
densenet_save_dir: pretrained_densenet  # DenseNet预训练模型保存基础目录
densenet_epochs: 50  # DenseNet预训练轮数 (仅在需要预训练时使用)

# 其它
gumble_tau: 1